### 删除索引
DELETE {{host}}/{{index}}


### 创建索引
PUT {{host}}/{{index}}
Content-Type: application/json

{
  "settings": {
    "analysis": {
      "analyzer": {
        "custom_analyzer": {
          "tokenizer": "ik_max_word",
          "filter": "custom_pinyin"
        }
      },
      "filter": {
         "custom_pinyin": {
           "type": "pinyin",
           "keep_original": true,
           "keep_full_pinyin": true,
           "keep_joined_full_pinyin": true,
           "keep_first_letter": false,
           "lowercase": true,
           "limit_first_letter_length": 16,
           "remove_duplicated_term": true
         }
      }
    }
  },
  "mappings": {
    "properties": {
    "ids": {
      "type": "long"
    },
    "age": {
      "type": "integer"
    },
    "sex": {
      "type": "byte"
    },
    "grade": {
      "type": "short"
    },
    "salary": {
      "type": "float"
    },
    "location": {
      "type": "double"
    },
    "name": {
      "type": "keyword"
    },
    "remark": {
      "type": "text",
      "analyzer": "custom_analyzer"
    },
    "description": {
      "type": "text"
    }
  }
  }
}

### 插入文档
POST http://localhost:9200/_bulk
Content-Type: application/json

< ./target.json