
### 删除索引
DELETE {{host}}/{{index}}


### 创建索引
PUT {{host}}/{{index}}
Content-Type: application/json

{
  "settings": {
    "analysis": {
      "analyzer": {
        "custom_analyzer": {
          "tokenizer": "ik_max_word",
          "filter": ["custom_pinyin"]
        }
      },
      "filter": {
         "custom_pinyin": {
           "type": "pinyin",
           "keep_original": true,
           "keep_full_pinyin": false,
           "keep_joined_full_pinyin": true,
           "keep_first_letter": false,
           "lowercase": true,
           "limit_first_letter_length": 16,
           "remove_duplicated_term": true,
           "keep_none_chinese": false
         },
        "pinyin_length_filter": {
          "type": "length",
          "min": 2
        }
      }
    }
  },
  "mappings": {
    "properties": {
    "ids": {
      "type": "long"
    },
    "age": {
      "type": "integer"
    },
    "sex": {
      "type": "byte"
    },
    "grade": {
      "type": "short"
    },
    "salary": {
      "type": "float"
    },
    "location": {
      "type": "double"
    },
    "name": {
      "type": "keyword"
    },
    "remark": {
      "type": "text",
      "analyzer": "custom_analyzer"
    },
    "description": {
      "type": "text",
      "analyzer": "custom_analyzer",
      "search_analyzer": "ik_smart"
    }
  }
  }
}

### 添加文档
POST {{host}}/{{index}}/_doc
Content-Type: application/json

{
  "remark": "汽车在过减速带时悬挂发出巨大的撞击声。",
  "description": "汽车在过减速带时悬挂发出巨大的撞击声。"
}
### 添加文档
POST {{host}}/{{index}}/_doc
Content-Type: application/json

{
  "remark": "轮胎出现鼓包，且有漏气现象。",
  "description": "轮胎出现鼓包，且有漏气现象。"
}
### 添加文档
POST {{host}}/{{index}}/_doc
Content-Type: application/json

{
  "remark": "安全气囊指示灯常亮。",
  "description": "安全气囊指示灯常亮。"
}
### 添加文档
POST {{host}}/{{index}}/_doc
Content-Type: application/json

{
  "remark": "变速箱换挡时有明显的冲击感。",
  "description": "变速箱换挡时有明显的冲击感。"
}
### 添加文档
POST {{host}}/{{index}}/_doc
Content-Type: application/json

{
  "remark": "燃油表显示不准确，油箱实际油量与显示不符。",
  "description": "燃油表显示不准确，油箱实际油量与显示不符。"
}
### 添加文档
POST {{host}}/{{index}}/_doc
Content-Type: application/json

{
  "remark": "发动机冷却液频繁泄漏。",
  "description": "发动机冷却液频繁泄漏。"
}
### 添加文档
POST {{host}}/{{index}}/_doc
Content-Type: application/json

{
  "remark": "刹车踏板行程变长，刹车效果减弱。",
  "description": "刹车踏板行程变长，刹车效果减弱。"
}
### 添加文档
POST {{host}}/{{index}}/_doc
Content-Type: application/json

{
  "remark": "汽车电路频繁短路，保险丝熔断。",
  "description": "汽车电路频繁短路，保险丝熔断。"
}

