### 同义词索引, 在配置文件中配置好同义词


### 删除索引
DELETE {{host}}/synonyms-index

### 创建索引
PUT {{host}}/synonyms-index
Content-Type: application/json

{
  "settings": {
    "analysis": {
      "analyzer": {
        "synonyms_analyzer": {
          "tokenizer": "ik_smart",
          "filter": [
            "doc_synonym"
          ]
        }
      },
      "filter": {
        "doc_synonym": {
          "type": "synonym",
          "synonyms_path": "synonyms.txt"
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "name": {
        "type": "text",
        "analyzer": "synonyms_analyzer"
      }
    }
  }
}

### 添加文档
POST {{host}}/synonyms-index/_doc
Content-Type: application/json

{
  "name": "苹果手机"
}